### ISSUE TITLE
separate Jingles better from main stream

### ISSUE THREAD

**Issue by weego** [adcxyz/futurevoices#7]
e.g. with 2 Buses on which Jingles and mainstream play.

**Comment by adcxyz** [comment]
idea: embed jingles in director task, so we know the compositions are silent during jingle.
options:

1. time structures for compositions predecided, then jingle;
2. play out composition until a natural end-of-soundfile, then jingle;
- and only do forced end at full hour?

**Comment by adcxyz** [comment]
Option 2  could work by compos-tdefs setting the remaintime of director so they 
end when the next file ends.

**Comment by adcxyz** [comment]
compositions adjust their endings now, so they always finish their last soundfile;
jingles are embedded now, and always play after a new quarter-hour has begun:
e.g.: 
comp X ends at 12:58 // no jingle
comp Y begins at 12:58, ends at 13:01:12: -> new quarter, so jingle.
